package app.market.mapper;

import app.market.model.FoodType;
import app.market.model.FoodTypeExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface FoodTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table food_type
     *
     * @mbg.generated Fri Nov 23 12:15:53 KST 2018
     */
    long countByExample(FoodTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table food_type
     *
     * @mbg.generated Fri Nov 23 12:15:53 KST 2018
     */
    int deleteByExample(FoodTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table food_type
     *
     * @mbg.generated Fri Nov 23 12:15:53 KST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table food_type
     *
     * @mbg.generated Fri Nov 23 12:15:53 KST 2018
     */
    int insert(FoodType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table food_type
     *
     * @mbg.generated Fri Nov 23 12:15:53 KST 2018
     */
    int insertSelective(FoodType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table food_type
     *
     * @mbg.generated Fri Nov 23 12:15:53 KST 2018
     */
    List<FoodType> selectByExample(FoodTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table food_type
     *
     * @mbg.generated Fri Nov 23 12:15:53 KST 2018
     */
    FoodType selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table food_type
     *
     * @mbg.generated Fri Nov 23 12:15:53 KST 2018
     */
    int updateByExampleSelective(@Param("record") FoodType record, @Param("example") FoodTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table food_type
     *
     * @mbg.generated Fri Nov 23 12:15:53 KST 2018
     */
    int updateByExample(@Param("record") FoodType record, @Param("example") FoodTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table food_type
     *
     * @mbg.generated Fri Nov 23 12:15:53 KST 2018
     */
    int updateByPrimaryKeySelective(FoodType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table food_type
     *
     * @mbg.generated Fri Nov 23 12:15:53 KST 2018
     */
    int updateByPrimaryKey(FoodType record);
}